spring:
  application:
    name: eureka-server #应用名称

#端口
server:
  port: 8761

# 配置Eureka Server 注册中心
eureka:
  instance:
    hostname: eureka01    #主机名
    prefer-ip-address:  true  # 是否使用ip地址注册
    instance-id:  ${spring.cloud.client.ip-address}:${server.port}
  client:
    register-with-eureka: false # 表示不向注册中心注册
    fetch-registry: false # 由于注册中心的职责就是维护服务实例，所以它不需要去检索服务
    #设置服务注册中心地址，指向另一个注册中心
    service-url:  # 注册中心对外暴露的注册地址
      defaultZone:  http://localhost:8762/eureka/
